services:
  nestapp:
    image:
    ports:
      - '4001:4000'
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
